apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ats.cnat.peterochodo.info
spec:
  group: cnat.peterochodo.info
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                command:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
  names:
    kind: At
    plural: ats
  scope: Namespaced
